### ISSUE TITLE
Request permission to start GPS without navigating to new Activity

### ISSUE THREAD

**Issue by chintan-mishra** [NewtronLabs/EasyPermissions#1]
Redirected here from a SOF QnA

As the topic header states, I want to start user device's GPS without navigating to a new activity. Can I get this done by using `EasyPermission`?

The usual way would be to use Google Play Services which we are currently using but we would like to migrate away from Google libraries.

**Comment by NewtronLabs** [comment]
Hi @chintan-mishra,

Thanks for contacting regarding Easy Permissions. You can request permissions by using this line:
`EasyPermissions.getInstance().requestPermissions(this, this);`

You can do this from anywhere, an `Activity` is not needed. 

We hope that helps,
Newtron Labs
