### ISSUE TITLE
Can't read classes

### ISSUE THREAD

**Issue by afaideen** [NewtronLabs/EasyPermissions#3]
error: error reading C:\Users\han\.gradle\caches\transforms-1\files-1.1\easypermissions-2.2.2.aar\d736c6feffd6d838aa0a4c1a74676b5b\jars\classes.jar; error in opening zip file

Fail to compile with android studio v3.1.4

**Comment by afaideen** [comment]
It has problem to integrate with other libraries.

**Comment by NewtronLabs** [comment]
Hi @afaideen!

We are looking into your issue. Could you provide your `build.gradle` for both the app and the project? 

Thank you,
Newtron Labs

**Comment by afaideen** [comment]
[Newtron.zip](https://github.com/NewtronLabs/EasyPermissions/files/2299376/Newtron.zip)

**Comment by NewtronLabs** [comment]
Hi @afaideen! 

Thank you for including the `build.gradle` file. After analyzing the files you sent we have realized the issue is a result of placing the plugin in your app gradle and not in the root gradle as the instructions show. Please ensure that your root gradle includes the following code snippet:

```
subprojects {
    apply plugin: 'com.newtronlabs.android'
}
``` 

Let us know if you still see the problem.

Cheers,
Newtron Labs

**Comment by afaideen** [comment]
yes I changed it but the problem still persisted.

**Comment by NewtronLabs** [comment]
Hi @afaideen! 

Could you send us a minimal reproducible example?  For connivence you can add it here on Github. 

Thanks,
Newtron Labs

**Comment by afaideen** [comment]
Hi Good morning, you may visit the code i'm working with at my github addressed, 
https://github.com/afaideen/MyEasyPermission

**Comment by NewtronLabs** [comment]
Hi @afaideen! 

Thank you. While we address this issue we recommend that you rename your `animators` module to ensure that it is below the `app` module in the hierarchy so that your issue goes away. In the meantime we will continue our analysis of the issue. 

Thanks,
Newtron Labs

**Comment by transfer1992** [comment]
Hi! 
Is there any progress on this?
I detected, that this bug occurs for me only after I have cleaned my gradle's cache folder completely - then the build will fail. However, if I then remove only the EasyPermissions lib files and run the build process again, it will download only EasyPermissions lib and the build will succeed. 
My workaround is to remove EasyPermissions from cache folder before every build (although I could do it only once after empty cache is populated).

**Comment by NewtronLabs** [comment]
Hi Han!

My most sincere apologies. Normally we reply to emails as quick as possible
but for some reason we missed your emails and they got sent to spam.

Good catch. We are currently working on resolving this issue. It seems that
using .gradlew assemble works then you can sync. However, if you sync first
then build it will give you problems.

We will get back to you shortly. Again sorry for the late reply!


 A team that cares, a company that delivers!
