### ISSUE TITLE
Need update to android gradle 3.2 for sdk 28

### ISSUE THREAD

**Issue by benjaminVadon** [NewtronLabs/EasyPermissions#4]
Using last version provided on you artifactory public repo, it is impossible to build with the new released Android Studio 3.2 which use : 'com.android.tools.build:gradle:3.2.0'

Can you provide a new version of EasyPermissions updated to last android sdk (pointing sdk 28) ?

Thanks 

PS: yes I know, new AS version was released only few days ago on stable branch ;)

**Comment by NewtronLabs** [comment]
Hi @benjaminVadon! 

We shall be releasing a new version with SDK 28 soon. We will let you know ASAP. We apologize for the delay as we have been in the process of releasing a new product. 

Cheers,
Newtron Labs
