### ISSUE TITLE
Can't locate         classpath 'com.newtronlabs.android:plugin:2.0.5-alpha'

### ISSUE THREAD

**Issue by guediagael** [NewtronLabs/EasyPermissions#5]
classpath 'com.newtronlabs.android:plugin:2.0.5-alpha' can not be found. The latest I could use was the version 2.0.3

**Comment by NewtronLabs** [comment]
Hi @guediagael,

Thank you for reaching out to us and identifying this issue. Please use `2.0.3-alpha`. 

Let us know if you run into any new issues. We are here to help.

Thank you,
Newtron Labs
