### ISSUE TITLE
Maximum supported Gradle version is 3.3.+

### ISSUE THREAD

**Issue by warcello** [NewtronLabs/EasyPermissions#6]
Can you upgrade this to the newest version?

**Comment by NewtronLabs** [comment]
Hi @warcello!

Thank you for reaching out. Could you share with us what version of the plugin you are using? It will help us narrow down the issue for you.

Thank you,
Newtron Labs

**Comment by warcello** [comment]
The one from readme file:
`com.newtronlabs.android:plugin:2.0.4-alpha`

And gradle plugin:
`org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31`
`com.android.tools.build:gradle:3.4.1`

with gradle version 5.1.1
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip`

**Comment by transfer1992** [comment]
Hello!
How is this issue going?
I might help with my issue I described in https://github.com/NewtronLabs/EasyPermissions/issues/3#issuecomment-492179394

**Comment by NewtronLabs** [comment]
We appreciate the patience. The issue has been resolved in latest version 3.0.0.

**Comment by transfer1992** [comment]
Thanks! Will try it out!
