### ISSUE TITLE
EasyPermissions in a ContentProvider

### ISSUE THREAD

**Issue by Soquar** [NewtronLabs/EasyPermissions#7]
I tried to use EasyPermission in a ContentProvider like this

public class MyContentProvider extends ContentProvider implements IPermissionsListener {
 @Override
    public boolean onCreate() {
            EasyPermissions.getInstance().requestPermissions(this, Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_BACKGROUND_LOCATION);
            }
}
but i didnt get the permissions. I have both permissions in the manifest.

Is EasyPermissions also available in ContentProviders or only in services?
If yes, what have i done wrong?

**Comment by NewtronLabs** [comment]
Hi @Soquar,

The library should work on a `ContentProvider`. We will investigate to make sure there are no issues and get back to you.

Thank you,
Amy

**Comment by NewtronLabs** [comment]
Hi @Soquar,

You are correct, there is a race condition with `ContentProviders` in the newer versions of Android. One of our engineers is already working on a solution and we will have a new version for you ASAP! In the meantime if you pass in `context` then it will work for you.

Thank you for your feedback!
Amy

**Comment by NewtronLabs** [comment]
Hi @Soquar,

We have a fix for you, please upgrade to version:

`compileOnly 'com.newtronlabs.easypermissions:easypermissions:4.1.0-beta01' `

Let us know if you run into any issues.

**Comment by Soquar** [comment]
Thank you for your fast respond.

Sadly, also with version 4.1.0-beta01 i didn't get the permissions with the call in my first post.
How should i pass the context in the call?

Thank you in advance

**Comment by NewtronLabs** [comment]
> Thank you for your fast respond.
> 
> Sadly, also with version 4.1.0-beta01 i didn't get the permissions with the call in my first post.
> How should i pass the context in the call?
> 
> Thank you in advance

That is quite odd but we will test more. This is how you pass in `context`:

`EasyPermissions.getInstance().requestPermissions(context, new IPermissionsListener());`

Notice that you don't need to pass in the permission list. The library fetches them from the manifest.

Please let us know how it goes,
Amy

**Comment by Soquar** [comment]
i cant use it like you described, because android studio tells me there is a mistake.

i can use it like        
`
EasyPermissions.getInstance().requestPermissions(context, new IPermissionsListener() {
                @Override
                public void onFailure(@NotNull Throwable throwable) {
                }

                @Override
                public void onCompleted(@NotNull Set<String> set, @NotNull Set<String> set1) {
                }
            };`
but sadly, i dont get the permissions from the Manifest.

Maybe you are getting different results because i install the contentprovider app, but it never gets started by hand. It just gets called by different apps.

**Comment by NewtronLabs** [comment]
Hello @Soquar,

If you add a log to your ContentProvider's `onCreate()` does it print?

Also, if you could make a small reproducible example and put it on Github we could take a look at it. We recently tested on device farm and the feature is working so something else could be happening, but we would still love to help you out.

Regards,
Amy
