### ISSUE TITLE
issue on gradle 4.0.1

### ISSUE THREAD

**Issue by kadaluarsa** [NewtronLabs/EasyPermissions#8]
Hey guys thanks for the awesome library now i can call permission anywhere but i think the library not support newer version of gradle, because i got an error its said only support gradle 3.5+ at compile time

**Comment by NewtronLabs** [comment]
Hello @kadaluarsa,

We released a new version that works on 3.6. We still need to release a version that works on the latest gradle. For now the highest we can support is 3.6.

Please look at the new `README.md` which contains the new version number.

Thanks for bringing this to our attention.

Thanks,
Amy

**Comment by NewtronLabs** [comment]
@kadaluarsa The latest version of the library supports gradle version `7.0.0`.
